name: pdfrx_example
description: "Demonstrates how to use the pdfrx plugin."
publish_to: 'none'

environment:
  # Flutter 3.16/Dart 3.2
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter

  pdfrx:
    path: ../

  cupertino_icons: ^1.0.6
  rxdart: ^0.27.7

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
