name: pdfrx
description: "Yet another PDF renderer for Flutter using PDFium."
version: 0.3.6
homepage: https://github.com/espresso3389/pdfrx

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  ffi: ^2.1.0
  flutter:
    sdk: flutter
  http: ^1.1.2
  js: ^0.6.7
  rxdart: ^0.27.7
  synchronized: ^3.1.0
  vector_math: ^2.1.4

dev_dependencies:
  ffigen: ^10.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
        sharedDarwinSource: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
        sharedDarwinSource: true
      windows:
        ffiPlugin: true
