name: pdfrx
description: "Yet another PDF renderer for Flutter using PDFium."
version: 0.1.1
homepage: https://github.com/espresso3389/pdfrx

environment:
  sdk: '>=3.2.0 <4.0.0'
  # Flutter versions prior to 3.7 did not support the
  # sharedDarwinSource option.
  flutter: '>=3.7.0'

dependencies:
  ffi: ^2.1.0
  flutter:
    sdk: flutter
  js: ^0.6.7
  rxdart: ^0.27.7
  synchronized: ^3.1.0
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  ffigen: ^10.0.0

flutter:
  plugin:
    platforms:
      android:
        package: jp.espresso3389.pdfrx
        pluginClass: PdfrxPlugin
      ios:
        package: jp.espresso3389.pdfrx
        pluginClass: PdfrxPlugin
        sharedDarwinSource: true
      windows:
        package: jp.espresso3389.pdfrx
        pluginClass: PdfrxPluginCApi
      linux:
        package: jp.espresso3389.pdfrx
        pluginClass: PdfrxPlugin
      macos:
        package: jp.espresso3389.pdfrx
        pluginClass: PdfrxPlugin
        sharedDarwinSource: true
ffigen:
  output:
    bindings: 'lib/src/pdfium_bindings.dart'
  headers:
    entry-points:
      - '../pdfrx/android/.lib/include/fpdfview.h'
    include-directives:
      - '../pdfrx/android/.lib/include/**'
  name: 'pdfium'
